### PR TITLE
Add `type="button"` to prevent submits when used inside a form

### PR DESCRIPTION
**Pull request by astronomersiva**
Thanks for this amazing library!

I upgraded from 0.3.2 and noticed that when pickr is used inside forms, the form is submitted on opening the color picker. This is because, the buttons do not have a `type="button"` attribute and hence defaults to a value of `submit` which ends up submitting the form.

I have added `type="button"` in all buttons in the code.

### CODE REVIEW

**Comment by Simonwep** [comment]
Wow, never thought a `button` could have (or it would make sence) a `type="button"` prop 😅 
Thanks!

**Comment by Simonwep** [comment]
Please note that the package was moved from `pickr-widget` to `@simonwep/pickr`!

**Comment by astronomersiva** [comment]
@Simonwep, can you please release this and other merged commits after 0.4.3 as a new version?

I am currently pointing to the GitHub link instead of a version in package.json and it will make things simpler especially inside corporate networks that usually restrict outbound network calls.

**Comment by Simonwep** [comment]
@astronomersiva Exactly what I wanted :) Give me 5min.

**Comment by astronomersiva** [comment]
Thanks a ton @Simonwep 👍 I can see 0.4.4 in the registry now

**Pull request merged**
