### PR TITLE
Rebuilt to fix junk output in pickr.min.css - 0.6.2

### PR DESCRIPTION
**Pull request by dotKev**
For https://github.com/Simonwep/pickr/issues/91

### CODE REVIEW

**Comment by Simonwep** [comment]
I'm a little bit confused why webpack added the wildcards `js.map*/ap*`, anyway.
I'll also update the versions on the next minor / patch - I don't think this is worth a patch version since only
image
Changed. And changing the version without publishing a new release can lead to confusion :/ Could you Change the version back to `0.6.1`, then I'll merge it :)

**Comment by dotKev** [comment]
I don't understand why the `dist/*min.js*` files are different sizes now? They should be the same.

**Comment by dotKev** [comment]
The `pickr.min.css` file had the old, broken sourcemapURL string on last built (same as you had generated.) Just RE-RE-built it and now it is updated. Very confused.

**Comment by Simonwep** [comment]
So much confusion haha, anyway - thanks :)

**Pull request merged**
