### PR TITLE
Fix support for IE11 in es5 build

### PR DESCRIPTION
**Pull request by rshatch**
-Add core-js@3 as a dependency
-Add preset-env configurations for core-js in es5 build config
-Keep webpack from transpiling core-js and babel libraries (see https://github.com/zloirock/core-js/issues/514 )

### CODE REVIEW

**Comment by rshatch** [comment]
(I don't love the `loose: true`, but I also don't love having to support IE11 and yet here I am. `loose` is the only way I could figure to produce IE11-usable JS with `useBuiltIns: 'usage'`)

**Comment by rshatch** [comment]
Yeah, unfortunately this was the smallest I could figure out and have it work, because unfortunately the existing es5 bundle only threw errors for me in IE11. If nothing else, hopefully other people who need IE11 support will see this :)

**Comment by Simonwep** [comment]
I'll take a look at it! There should at least be an _official_ way to use it within _things_ like ie11 :D 
Happy Halloween! ☠️ 👻

**Comment by Simonwep** [comment]
I'll merge it since if people really need to support IE11 they gonna need it (unfortunatly) :/

I've updated the README since the size-difference is quite big and adding polyfills later would be way better.

Thanks for the PR :)

**Pull request merged**
