### PR TITLE
Fix Swatches alignment with grid-gap

### PR DESCRIPTION
**Pull request by jackmcdade**
When you have just a couple of swatches, they're spaced super far apart because of the `justify-content: space-around;` css property. It looks pretty awkward. This fixes that.

This fiddle shows the alignment issue: <https://jsfiddle.net/yz7cb98q/>

### CODE REVIEW

**Comment by Simonwep** [comment]
Oh yeah, that's right... But I would actually just remove the `justify-content` since if the browser doesn't support `grid` and flex is used as fallback, the spaces-differences are kinda big. Moreover I wouldn't use `px` as unit as it's to _fixed_:

### Without `grid-gap`
##### `display: grid`
image
##### `display: flex`
image

### With `grid-gap: 10px`
##### `display: grid`
image
##### `display: flex`
image

**Comment by Simonwep** [comment]
I initially thought `justify-content: space-between` looks fine if there are just enough elements without gaps that big, maybe this could be dynamically applied :suspect:

**Comment by jackmcdade** [comment]
Right on, yeah good call, wasn't thinking about the y-axis (obviously, as my use case was just 2 or 3 swatches). That leftover whtiespace at the end there doesn't bother _me_ at all. 🤷‍♂

**Comment by Simonwep** [comment]
I'm thinking about auto-adjusting the alignment:

With centered alignment (get's only applied if the remaining space is less than one button or multiple rows of swatches exist):
image

Without:
image

So to clarify this, if the red area (marked in my previous comment) is less than one button `justify-content: center` gets applied to `pcr-swatches`, if not `justify-content: inherit`. Unfortunately this prop can't be animated so there's a _small_ jump between these props, any thoughts?

**Pull request merged**
