### PR TITLE
added workaround for some old androids with weird JS versions

### PR DESCRIPTION
**Pull request by Funkelfetisch**
forgot to send in this PR while it was recent.

This fixes errors with some Androids misinterpreting the datatype of a field.

### CODE REVIEW

**Comment by Simonwep** [comment]
What do you mean by "weird JS versions"? I generally do not intent to make any changes for specific JS engines which operate alongside the official ECMA specification...

**Comment by Funkelfetisch** [comment]
you don't "define" that variable as string, therefore some string functions don't work on a Oneplus 9t and Galaxy S..6?, if I remember correctly.
it's just a small workaround that will save somebody a lot of brainfuck, I don't understand why you wouldn't merge that. But OK.

**Comment by Simonwep** [comment]
You don't "define" any types in vanilla javascript... if it isn't "something with a match function" at runtime it'll result in an runtime error. Could you tell me what JS engines are used in your case? It obviously isn't any of the mainstream engines such as the V8, SpiderMonkey, Webkit or even Gecko....

**Comment by Simonwep** [comment]
Closing because of inactivity.

**Pull request closed without merging**
