### PR TITLE
Add option to add aria-label to input box.

### PR DESCRIPTION
**Pull request by adityatoshniwal**
I've made it optional.

### CODE REVIEW

**Comment by Simonwep** [comment]
Thanks, but I really don't think it should be optional, it's less space-consuming if we just add a aria-label such as "color input field" as adding a whole new option.
Moreover `strings` is a prototype of i18n support and not meant for this kind of purpose :/

**Comment by adityatoshniwal** [comment]
Exactly that's why I put it in strings. The aria label should be based on language. Hard coding will not allow other languages.

**Comment by Simonwep** [comment]
@adityatoshniwal
Yeah, but this would be the only `aria-label` with i18n support. We could do all this stuff (including base-sentences in english) in the [i18n branch](https://github.com/Simonwep/pickr/tree/i18n) and for all others too. If we have only one which is variable we may as well drop it and hardcode it.

**Comment by adityatoshniwal** [comment]
@Simonwep - the aria-label on the buttons are of not much use. Buttons are read by the strings options which allow i18n. Since there is no visible label for input like the buttons have, it has to be aria-label.

**Comment by Simonwep** [comment]
Well, there are buttons with no content at all such as the [previous-color button](https://github.com/Simonwep/pickr/blob/master/src/js/template.js#L14) and there are many `aria-labels` on `div` elements too.

> Since there is no visible label for input like the buttons have, it has to be aria-label.

What do you mean by that? I thought we were talking about the `aria-label` on the input-field? And the aria-labels on the buttons should be more descriptive which might not be necessary for the button-content itself.

**Comment by adityatoshniwal** [comment]
I would not argue further, sorry. Thought it would have been a better option. I'll make the changes to hard code it.
Thanks.

**Comment by Simonwep** [comment]
I want to move further i18n development to the corresponding branch and finish that once and for all, adding single `aria-labels` some with and some without translation possibilities doesn't make much sense.

If you want to add this feature you can always make a PR to [this branch / file](https://github.com/Simonwep/pickr/blob/i18n/src/js/template.js#L38) and use the `_t(key, fallback)` function to access translations / strings.

**Comment by adityatoshniwal** [comment]
OK. Thanks.

**Pull request closed without merging**
