### PR TITLE
chore: use npm ci

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by Simonwep** [comment]
I'm not really sure why this build did failed, it seems like `npm ci` hasn't installed any packages, what's the problem?

**Comment by DanielRuf** [comment]
We can close this as https://github.com/Simonwep/pickr/pull/2 is merged which is an alternative for improving the needed time for each build.

**Comment by DanielRuf** [comment]
https://travis-ci.org/Simonwep/pickr/builds/390652066#L448

Seems `--only-dev` can not be used with `npm ci`. Good to know.

**Comment by DanielRuf** [comment]
See https://github.com/zkat/cipm/issues/48

**Comment by Simonwep** [comment]
Thanks, perfect! I wasn't shre if `--only=dev` works.

**Pull request closed without merging**
